package storage

import (
	"strings"
	"testing"
)

func TestNewLocation(t *testing.T) {
	location := NewLocation("bucket", "object")
	if location.Bucket != "bucket" {
		t.Errorf("Bucket name looks odd, got: %s, want: %s", location.Bucket, "bucket")
	}
	if location.Object != "object" {
		t.Errorf("Object name looks odd, got: %s, want: %s", location.Object, "object")
	}
}

func TestNewLocationWithAutoGeneratedName(t *testing.T) {
	location := NewLocationWithAutoGeneratedName("bucket", "my/path")
	if location.Bucket != "bucket" {
		t.Errorf("Bucket name looks odd, got: %s, want: %s", location.Bucket, "bucket")
	}
	if !strings.HasPrefix(location.Object, "my/path/") {
		t.Errorf("Object name looks odd, got: %s, want: %s", location.Object, "object")
	}
}
