steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '--build-arg', 
         'PACKAGE=${_PACKAGE}',
         '-t', 
         'gcr.io/hpc-poc/${_PACKAGE}', 
         '.',
        '--file', 
        '${_DOCKERFILE}']
substitutions:
    _DOCKERFILE: Dockerfile # default value        
images:
- 'gcr.io/hpc-poc/${_PACKAGE}'


