apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: gcr.io/hpc-poc/monitor:latest
        env:
        - name: TEMPLATE_PATH
          value: /app
        - name: NAMESPACE
          value: default
      serviceAccount: monitor
      serviceAccountName: monitor