apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  selector:
    app: monitor
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer