apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: default
spec:
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-acc-key
      containers:
      - name: subscriber
        image: gcr.io/hpc-poc/orchestrator:latest
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BUSINESS_NAME
          value: bu1
        - name: PROJECT_NAME
          value: hpc-poc
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLOUD_STORAGE_BUCKET_NAME
          value: hpc-poc-bucket  
        - name: ENGINE_IMAGE
          value: "gcr.io/hpc-poc/engine:latest"  
      serviceAccount: job-engine
      serviceAccountName: job-engine