apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-bu3
  namespace: default
spec:
  selector:
    matchLabels:
      app: orchestrator-bu3
  template:
    metadata:
      labels:
        app: orchestrator-bu3
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-acc-key
      containers:
      - name: subscriber
        image: gcr.io/hpc-poc/orchestrator:latest
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BUSINESS_NAME
          value: bu3
        - name: TASK_LOAD_FACTOR
          value: "0.1"
        - name: MAX_PODS_PER_JOB
          value: "100"
        - name: PROJECT_NAME
          value: hpc-poc
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLOUD_STORAGE_BUCKET_NAME
          value: hpc-poc-bucket  
        - name: IMAGE_REGISTRY
          value: "gcr.io/hpc-poc"  
      serviceAccount: job-engine
      serviceAccountName: job-engine